[pytest]
addopts = --alluredir=reports/allure-results --html=reports/report.html --self-contained-html
python_files = test_*.py
python_classes = Test*
python_functions = test_*

markers =
    login
    invalidlogin
    emptyuser
    emptypass
    logout
    session
    navigation
    product
    cart
    positive
    filter
    negative